# Welcome to Jekyll!
#

# Site settings
title: Open Cities Africa
description: |
  Making urban planning data better by making it more open
owner: GFDRR # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opencities.ithacaweb.org" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
permalink: pretty
#sass:
#  style: compressed

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/resources/", text: "Resources"}
 - {permalink: "/accra/", text: "Accra"}
 - {permalink: "/antananarivo/", text: "Antananarivo"}
 - {permalink: "/brazzaville/", text: "Brazzaville"}
 - {permalink: "/kampala/", text: "Kampala"}
 - {permalink: "/kinshasa/", text: "Kinshasa"}
 - {permalink: "/monrovia/", text: "Monrovia"}
 - {permalink: "/ngaoundere/", text: "Ngaoundéré"}
 - {permalink: "/pointe-noire/", text: "Pointe-Noire"}
 - {permalink: "/saint-louis/", text: "Saint-Louis"}
 - {permalink: "/seychelles/", text: "Seychelles"}
 - {permalink: "/zanzibar-city/", text: "Zanzibar City"}
